{{-- resources/views/reports/dashboard.blade.php --}}
<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
body{font-family:'DejaVu Sans',sans-serif;font-size:11px;color:#2c3e50;margin:0;padding:25px;}
.header{background:linear-gradient(135deg,#2d8a4e,#1a6b9a);color:#fff;padding:20px 25px;margin:-25px -25px 25px;display:flex;justify-content:space-between;align-items:center;}
.header h1{margin:0;font-size:18px;}
.header .sub{font-size:9px;opacity:.8;margin-top:3px;}
.section{margin-bottom:20px;}
.section-title{font-size:12px;font-weight:800;color:#1a2e1e;border-bottom:2px solid #2d8a4e;padding-bottom:5px;margin-bottom:10px;}
.grid{display:flex;gap:10px;flex-wrap:wrap;}
.kpi{flex:1;min-width:100px;background:#f8fafc;border-radius:8px;padding:12px;text-align:center;border-top:3px solid #2d8a4e;}
.kpi .num{font-size:22px;font-weight:800;color:#2d8a4e;}
.kpi .lbl{font-size:8px;color:#888;margin-top:2px;}
.kpi.blue{border-top-color:#1a6b9a;}.kpi.blue .num{color:#1a6b9a;}
.kpi.orange{border-top-color:#e07b39;}.kpi.orange .num{color:#e07b39;}
.kpi.red{border-top-color:#dc3545;}.kpi.red .num{color:#dc3545;}
table{width:100%;border-collapse:collapse;margin-top:8px;}
th{background:#2d8a4e;color:#fff;padding:5px 8px;font-size:9px;}
td{padding:4px 8px;border-bottom:1px solid #f0f0f0;font-size:9px;}
.footer{margin-top:25px;text-align:center;font-size:8px;color:#aaa;border-top:1px solid #eee;padding-top:8px;}
</style></head>
<body>
<div class="header">
    <div>
        <h1>📊 {{ config('app.name') }}</h1>
        <div class="sub">{{ __('Dashboard Summary Report') }} — {{ $data['generated_at'] }}</div>
    </div>
    <div style="font-size:10px;text-align:right;">
        <div>{{ __('Generated by') }}: {{ auth()->user()?->name ?? 'System' }}</div>
    </div>
</div>

<div class="section">
    <div class="section-title">🗑 {{ __('Containers') }}</div>
    <div class="grid">
        <div class="kpi"><div class="num">{{ $data['containers']['total'] }}</div><div class="lbl">{{ __('Total Containers') }}</div></div>
        <div class="kpi red"><div class="num">{{ $data['containers']['needs_emptying'] }}</div><div class="lbl">{{ __('Needs Emptying') }}</div></div>
        <div class="kpi orange"><div class="num">{{ $data['containers']['avg_fill'] }}%</div><div class="lbl">{{ __('Avg Fill Level') }}</div></div>
    </div>
</div>

<div class="section">
    <div class="section-title">🚛 {{ __('Vehicles') }}</div>
    <div class="grid">
        <div class="kpi blue"><div class="num">{{ $data['vehicles']['total'] }}</div><div class="lbl">{{ __('Total Vehicles') }}</div></div>
        <div class="kpi"><div class="num">{{ $data['vehicles']['active'] }}</div><div class="lbl">{{ __('Active') }}</div></div>
        <div class="kpi blue"><div class="num">{{ $data['vehicles']['on_route'] }}</div><div class="lbl">{{ __('On Route') }}</div></div>
    </div>
</div>

<div class="section">
    <div class="section-title">🗺 {{ __('Routes Today') }}</div>
    <div class="grid">
        <div class="kpi"><div class="num">{{ $data['routes']['today_total'] }}</div><div class="lbl">{{ __('Scheduled') }}</div></div>
        <div class="kpi"><div class="num">{{ $data['routes']['today_completed'] }}</div><div class="lbl">{{ __('Completed') }}</div></div>
    </div>
</div>

<div class="section">
    <div class="section-title">⚠ {{ __('Complaints') }}</div>
    <div class="grid">
        <div class="kpi red"><div class="num">{{ $data['complaints']['open'] }}</div><div class="lbl">{{ __('Open Complaints') }}</div></div>
        <div class="kpi red"><div class="num">{{ $data['complaints']['urgent'] }}</div><div class="lbl">{{ __('Urgent') }}</div></div>
    </div>
</div>

<div class="footer">
    {{ config('app.name') }} — {{ __('Dashboard Summary') }} — {{ now()->format('Y-m-d H:i') }}
</div>
</body></html>
